logging:
  level:
    ROOT: info
    org.hibernate.SQL: INFO
    com.masqani.masqani: INFO

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_URL}:3306/${MYSQL_DB}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: tenancyTrack
  liquibase:
    contexts: prod
    default-schema: tenancyTrack