logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: DEBUG
    com.masqani.masqani: DEBUG

spring:
  profiles:
    active: dev
  application:
    name: masqani
  datasource:
      url: jdbc:mysql://localhost:3306/masqani?createDatabaseIfNotExist=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        poolName: Hikari
        auto-commit: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none #because of liquibase!
    properties:
      hibernate:
        default_schema: masqani
  liquibase:
    contexts: dev
    change-log: db/changelog/db.changelog-master.xml
    default-schema: masqani
    enabled: true
  #    drop-first: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
            redirect-uri: "http://localhost:9900/login/oauth2/code/google"
          provider:
            google:
              authorization-uri: https://accounts.google.com/o/oauth2/auth
              token-uri: https://oauth2.googleapis.com/token
              user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
              user-name-attribute: sub


  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 9090



#okta:
#  oauth2:
#    issuer: https://dev-w801unrgovy6ki0y.us.auth0.com/
#    client-id: ${AUTH0_CLIENT_ID}
#    client-secret: ${AUTH0_CLIENT_SECRET}
#
#application:
#  auth0:
#    role-landlord-id: rol_ZBYZ3WXJk1UzbZJu

