import {
  faAnchor,
  faBan,
  faBars,
  faBed,
  faBox,
  faBuilding,
  faChampagneGlasses,
  faChessRook,
  faCircle,
  faCircleNotch,
  faCity,
  faDollarSign,
  faEarthEurope,
  faExclamation,
  faEye,
  faFire,
  faHome, faHospitalUser, faHotel, faHouse, faHouseUser, faLightbulb, faMinus, faMugSaucer, faPeopleRoof, faPlus,
  faSearch, faSnowflake, faSquare, faTent, faTowerObservation, faTractor, faTrashCan, faTree,
  faUser, faUsers, faWarehouse, faWater,
  IconDefinition
} from "@fortawesome/free-solid-svg-icons";

export const fontAwesomeIcons: IconDefinition[] = [
  faAnchor,
  faBan,
  faBars,
  faBox,
  faChampagneGlasses,
  faChessRook,
  faCircle,
  faCircleNotch,
  faDollarSign,
  faEarthEurope,
  faExclamation,
  faEye,
  faFire,
  faHouse,
  faLightbulb,
  faMinus,
  faMugSaucer,
  faPlus,
  faSearch,
  faSnowflake,
  faTent,
  faTowerObservation,
  faTractor,
  faTrashCan,
  faTree,
  faUser,
  faWater,
  faBuilding,
  faSquare,
  faBed,
  faHome,
  faHotel,
  faHouseUser,
  faCity,
  faWarehouse,
  faUsers,
  faPeopleRoof,
  faHospitalUser
]
