package com.masqani.masqani.enums;

public enum RentalCategory {
    ALL,
    APARTMENTS,
    STUDIOS,
    BEDSITTERS,
    FARMHOUSES,
    HOSTELS,
    MANSIONETTES,
    TOWNHOUSES,
    DUPLEXES,
    VILLAS,
    BUNGALOWS,
    LOFTS,
    PENTHOUSES,
    CONDOS,
    SHARED_HOUSING,
    EXECUTIVE_HOMES,
    SINGLE_FAMILY_HOMES,
    CO_HOUSING,
    RETIREMENT_COMMUNITIES,
    MODULAR_HOMES
}